Add in a feature for defining a custom classpath for the launch configs
palantir/gradle-java-distribution pull request #128
Opened 2016-10-18 19:08 UTC by jfosco

You can now define a customClasspath for the distribution which will
override the expansion of all *.jar files in the runtime configuration.

2016-10-18 19:28 UTC, uschi2000 requested changes
(1) need to update readme
(2) what's the use case for this? the implementation seems fine module some nitpicks, but I don't quite understand the rationale.

2016-10-18 19:28 UTC, uschi2000 commented on src/test/groovy/com/palantir/gradle/javadist/JavaDistributionPluginTests.groovy
> +        expectedStaticConfig.setClasspath(['service/lib/manager.jar', 'service/lib/config.jar'])
can probably worry about this field only in the assertion

2016-10-18 19:28 UTC, uschi2000 commented on src/main/groovy/com/palantir/gradle/javadist/tasks/LaunchConfigTask.groovy
> +        if (distributionExtension().getCustomClasspath().size() == 0) {
isEmpty

2016-10-18 20:07 UTC, uschi2000 commented
further, we should fix the classpath at compile time; so it shouldn't contain `*` and other run-time -evaluated things like `../` etc

2016-10-20 17:57 UTC, uschi2000 requested changes

2016-10-20 17:57 UTC, uschi2000 commented on src/main/groovy/com/palantir/gradle/javadist/DistributionExtension.groovy
> +        assert customClasspath.every { isAllowedClasspathChar(it) }
should give more useful error of the form "Found foo, expected bar"

2016-10-20 17:57 UTC, uschi2000 commented on readme.md
> + * (optional) `customClasspath` a list of jars to put on the classpath instead of all jars in the
this is not quite complete enough. at the minimum, must say that these are file names relative to some path, that they must not contain certain characters, something about the classpath order

2016-10-20 17:57 UTC, uschi2000 commented on src/test/groovy/com/palantir/gradle/javadist/DistributionExtensionTest.groovy
> +            setCustomClasspath(['*', '..', ':', '/'])
every single one of them should throw, right?

2016-10-20 17:57 UTC, uschi2000 commented on src/test/groovy/com/palantir/gradle/javadist/JavaDistributionPluginTests.groovy
> +        runSuccessfully(':build', ':distTar', ':untar')
i actually believe this should fail if the classpath files are not readable

2016-10-21 16:40 UTC, jfosco commented on src/main/groovy/com/palantir/gradle/javadist/DistributionExtension.groovy
> +        assert customClasspath.every { isAllowedClasspathChar(it) }
If I use the custom classpath to filter against the list of jars originally used in the LaunchConfigTask, do I still need to check for special characters?

2016-10-21 17:10 UTC, uschi2000 commented on src/main/groovy/com/palantir/gradle/javadist/DistributionExtension.groovy
> +        assert customClasspath.every { isAllowedClasspathChar(it) }
IMO, it's fine to just check the custom ones

2016-10-21 22:51 UTC, jfosco commented on src/test/groovy/com/palantir/gradle/javadist/JavaDistributionPluginTests.groovy
> +        runSuccessfully(':build', ':distTar', ':untar')
Good point. I changed it to require that the customClasspath jars have to match actual dependency jars.

2016-10-22 04:25 UTC, uschi2000 commented
I still think this is a little convoluted, sorry. (I should have been more specific here from the start.) The default behaviour is to to use the concatenation of the jar and the runtime dependencies. I would propose to make provide an optional `FileCollection classpath` configuration point such that: if it is set, then this FileCollection becomes the classpath, else the default is the classpath (see above).

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/palantir/gradle-java-distribution/128#-KUecffZPyIUEj0gNIo6:-KUecffZPyIUEj0gNIo7:b-c6aubj) (no related file):*
Further, the ManifestClasspathJarTask must be updated accordingly, so this is likely a slightly bigger refactor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/gradle-java-distribution/128#-:-KUebVYXP3vjxwoW4rEj:boazdqi)*
<!-- Sent from Reviewable.io -->

2016-10-27 01:24 UTC, uschi2000 commented
So this PR is now about enabling the classpath jar, rather than about allowing to customize the classpath, right?

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/gradle-java-distribution/128#-:-KV2iyVxpcss5IU9_1kN:b9o7vqr)*
<!-- Sent from Reviewable.io -->

2016-10-27 01:33 UTC, uschi2000 commented
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/test/groovy/com/palantir/gradle/javadist/JavaDistributionPluginTests.groovy, line 338 at r3](https://reviewable.io:443/reviews/palantir/gradle-java-distribution/128#-KV2lBXmUkACP4ussLyq:-KV2lBXnHeEe2uFdyC0J:b-lu6uj7) ([raw file](https://github.com/palantir/gradle-java-distribution/blob/561434821bd8cd74a7bf3f95ad9f9697eee89433/src/test/groovy/com/palantir/gradle/javadist/JavaDistributionPluginTests.groovy#L338)):*
> ```Groovy
>     }
> 
>     def 'produces manifest-classpath jar and windows start script with no classpath length limitations'() {
> ```

stale test name

---

*[src/test/groovy/com/palantir/gradle/javadist/JavaDistributionPluginTests.groovy, line 362 at r3](https://reviewable.io:443/reviews/palantir/gradle-java-distribution/128#-KV2lEcfuICOMRZtUXwT:-KV2lEcfuICOMRZtUXwU:b3ofc27) ([raw file](https://github.com/palantir/gradle-java-distribution/blob/561434821bd8cd74a7bf3f95ad9f9697eee89433/src/test/groovy/com/palantir/gradle/javadist/JavaDistributionPluginTests.groovy#L362)):*
> ```Groovy
>         String launcher = file('dist/service-name-0.1/service/bin/launcher-static.yml', projectDir).text
>         !launcher.contains("external.jar")
>     }
> ```

would like to see an end-to-end test for launching the service through the unix classpath jar

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/gradle-java-distribution/128)*
<!-- Sent from Reviewable.io -->

2016-10-27 01:33 UTC, uschi2000 commented
Reviewed 5 of 7 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palantir/gradle-java-distribution/128)*
<!-- Sent from Reviewable.io -->

2016-10-27 21:06 UTC, jfosco commented
Done, but producing a manifest classpath jar is busted until you merge in YY's commit fixing how the plugin reaches into the gradle object model

2017-01-25 16:08 UTC, uschi2000 commented
Closing since there wasn't much  movement. Feel free to reopen if this is still an issue.

2017-01-25 16:08 UTC, closed without merging