Do not force dependency resolution during configuration phase
palantir/gradle-java-distribution pull request #131
Opened 2016-10-19 19:06 UTC by lee467

For example, accessing project.configurations.runtime during
configuration phase (.../blob/0.9.0/.../ManifestClasspathJarTask.groovy#L36)
slows down all the other tasks in the project that uses this plugin.

2016-10-19 19:06 UTC, palantirtech commented
Thanks for your interest in [palantir/gradle-java-distribution](https://github.com/palantir/gradle-java-distribution), @lee467! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

2016-10-20 17:51 UTC, uschi2000 requested changes
looks good modulo SHOUTING

2016-10-20 17:51 UTC, uschi2000 commented on src/main/groovy/com/palantir/gradle/javadist/tasks/DistTarTask.groovy
> +        // DO NOT ACCESS RUNTIME CONFIGURATIONS IN THIS CLOSURE AS IT WILL FORCE DEPENDENCY
SHOUTING not required :)

2016-10-20 17:51 UTC, uschi2000 commented on src/main/groovy/com/palantir/gradle/javadist/tasks/RunTask.groovy
> +        // DO NOT ACCESS RUNTIME CONFIGURATIONS IN THIS CLOSURE AS IT WILL FORCE DEPENDENCY
as above

2016-10-21 20:47 UTC, uschi2000 approved these changes

2016-10-21 20:48 UTC, merged